version: '3.7'
services:
  mysql:
    image: mysql:8.0.28
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var1/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass

  postgres:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql      
    environment:
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_DB=appps
      - POSTGRES_USER=userps
      - POSTGRES_PASSWORD=passps

  node-app:
    build: ./gate-simulator
    image: node-app:1.0
    ports:
      - 9999:9999